# src/configuration/constants.py

# XGBoost hyperparameter search ranges
N_ESTIMATORS_MIN = 50
N_ESTIMATORS_MAX = 500

LEARNING_RATE_MIN = 1e-4
LEARNING_RATE_MAX = 0.3

MAX_DEPTH_MIN = 3
MAX_DEPTH_MAX = 10

SUBSAMPLE_MIN = 0.5
SUBSAMPLE_MAX = 1.0

COLSAMPLE_BYTREE_MIN = 0.5
COLSAMPLE_BYTREE_MAX = 1.0

MIN_CHILD_WEIGHT_MIN = 1
MIN_CHILD_WEIGHT_MAX = 10

# Evaluation settings
MIN_TEST_FRACTION = 0.05
OPTIMAL_EVALUATION_POINTS = 100
